version: "3"

services:
  nginx:
    image: umputun/nginx-le:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./data/etc/ssl:/etc/nginx/ssl
      - ./nginx-service.conf:/etc/nginx/service.conf
    ports:
      # primary host interface only
      - "10.0.0.75:80:80"
      - "10.0.0.75:443:443"
    environment:
      - TZ=Europe/Amsterdam
      - LETSENCRYPT=true
      - LE_EMAIL=alexander.shchapov@gmail.com
      - LE_FQDN=highlighter.darednaxella.name

  redis:
    restart: unless-stopped
    image: redis:alpine
    expose:
     - 6379
    volumes:
      - ./data:/data
  app:
    restart: unless-stopped
    build: .
    environment:
      - PRODUCTION=1
    expose:
      - 8000
    depends_on:
      - redis
