version: "2"
services:
  redis:
    image: redis
    volumes:
      - ./data:/data
  app:
    environment:
      - PROD=1
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/src/app
    depends_on:
      - redis
