version: "2"
services:
  redis:
    image: redis
    volumes:
      - ./data:/data
  app:
    image: alexanderad/highlighter:latest
    environment:
      - PRODUCTION=1
    ports:
      - 8000:8000
    depends_on:
      - redis
